stages:
  - test

before_script:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --no-scripts --quiet --ignore-platform-reqs
  - cp app/config/parameters.yml.dist app/config/parameters.yml

run_tests:
  image: sumocoders/framework-php71:latest
  script:
    - SYMFONY_DEPRECATIONS_HELPER=weak bin/phpunit -c app/
  stage: test
  tags:
    - php71
    - docker

code_styles:
  image: sumocoders/framework-php71:latest
  script:
    - bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 src/
  stage: test
  tags:
    - php71
    - docker
