before_script:
  - php /composer.phar install --no-progress --no-scripts
  - cp app/config/parameters.yml.dist app/config/parameters.yml

run_tests:
  image: php:7.1
  script:
    - SYMFONY_DEPRECATIONS_HELPER=weak bin/phpunit -c app/
  stage: test
  tags:
    - php71
    - docker

code_styles:
  image: php:7.1
  script:
    - bin/phpcs --standard=psr2 --extensions=php --warning-severity=0 src/
  stage: test
  tags:
    - php71
    - docker
