sudo: false

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=7

language: php

matrix:
  include:
    - php: 5.5
    - php: 5.6
    - php: 7
    - php: nightly
    - php: hhvm
  allow_failures:
    - php: 5.5
    - php: nightly
    - php: hhvm

before_script:
  - composer self-update
  - mysql -e 'create database app_test'
  - "sed 's/database_name:*/database_name: app_test/' app/config/parameters.yml.dist | sed 's/database_user:*/database_user: travis/' | sed 's/database_password:*/database_password:/' > app/config/parameters.yml"
  - composer install --prefer-source --no-interaction --no-scripts
  - composer run-script post-travis
  - php app/console doctrine:migration:migrate --env=test --no-interaction
#  - php app/console doctrine:fixtures:load --env=test --no-interaction

  # install required gulp-packages
  - npm install gulp@"^3.9.0" gulp-rename@"^1.2.2" gulp-coffee@"^2.3.1" gulp-util@"^3.0.6"

  # create some bogus files
  - mkdir -p web/assets/css && touch web/assets/css/style.css

  # generate all required assets
  - gulp --gulpfile gulp-travis.js build
  - php app/console assets:instal --env=test

script:
  - bin/phpunit -c app/ --coverage-clover=coverage.clover

after_success:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
