version: '2'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: root
    image: mysql:5.5
    ports:
      - 3306:3306
    restart: always
    volumes:
      - "~/Sites/sumocoders/docker/mysql55:/var/lib/mysql"

  web:
    # this requires the sumocoders-images to be installed
    image: sumocoders/framework-php71:latest
    depends_on:
      - mysql
    environment:
      - SYMFONY_ENV=dev
      - SYMFONY_DEBUG=1
    links:
      - mysql
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./:/var/www/html:cached
      - ~/.ssh/:/var/www/.ssh:ro
