services:
  sumo_coders.user.repository.sumo_user:
    class: SumoCoders\FrameworkUserBundle\Repository\SumoUserRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - SumoCodersFrameworkUserBundle:SumoUser

  sumo_coders.user.repository.admin:
    class: SumoCoders\FrameworkUserBundle\Repository\AdminRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - SumoCodersFrameworkUserBundle:Admin
