imports:
    - { resource: config.yml }

# Set our own exception controller so we can show nice pages
twig:
    exception_controller: SumoCodersFrameworkCoreBundle:Exception:onException

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
            max_files: 10
        console:
            type: console
            process_psr_3_messages: false

# Sentry configuration
sentry:
  dsn: '%sentry.dsn%'
