_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_errors:
    resource: "@SumoCodersFrameworkErrorBundle/Resources/config/routing.yml"
    options:
      i18n: false

_main:
    resource: routing.yml

sumo_coders_example_bundle:
  resource: "@SumoCodersFrameworkExampleBundle/Resources/config/routing.yml"
  prefix: /example

JMSTranslationBundle_ui:
    resource: @JMSTranslationBundle/Controller/
    type:     annotation
    prefix:   /_trans
