security:
    encoders:
        SumoCoders\FrameworkMultiUserBundle\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        multi_user_bundle:
            id: sumocoders.user_provider

    firewalls:
        main:
            provider: multi_user_bundle
            pattern: ^/
            anonymous: ~
            guard:
              authenticators:
                - sumocoders.form_authenticator
            logout:
              path:   /%locale%/logout
              target: /
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/(_(profiler|wdt|tests)|css|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/locale.json, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
