security:
    encoders:
        SumoCoders\FrameworkMultiUserBundle\Entity\BaseUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        sumocoders.multi_user_provider:
            id: sumocoders.user_provider

    firewalls:
        main:
            provider: sumocoders.multi_user_provider
            logout:
                path: multi_user_logout
                target: /
            anonymous: ~
            guard:
                authenticators:
                    - sumocoders.form_authenticator
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/\w\w/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/request-password-reset, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/reset-password, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt|tests)|css|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/locale.json, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/user/\d+/edit-user, role: ROLE_USER }
        - { path: ^/\w\w/user, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
